name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t express-ssr-app:latest .

      - name: Save Docker image to tarball
        run: docker save express-ssr-app:latest -o image.tar

      - name: Copy image to remote server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "image.tar,docker-compose.yml"
          target: "~/express-ssr-app"

      - name: List files before SCP
        run: ls -lah

      - name: Load and run Docker image on remote server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/express-ssr-app
            docker load -i image.tar
            docker compose down || true
            docker compose up -d